# Generated by Django 5.1.7 on 2025-12-29 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_staffavailability_delete_timeslot'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='staffavailability',
            name='day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of month (1-31). If null, applies to entire month', null=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='staff_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of available staff for this period'),
        ),
       
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='store_block_start_t_11cf37_idx')],
            },
        ),
    ]

