# Generated by Django 5.0 on 2026-05-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_blockedslot_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together=set(),
        ),
    ]
